

CREATE TABLE pix_expense (

    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    expense_id BIGINT,
    source_bank_acc_id BIGINT,
    destination_bank_name VARCHAR(50) NOT NULL COMMENT 'No need to keep track of all more complex bank data, since what only matters is the user, who sends it',
    pix_key VARCHAR(40) NOT NULL COMMENT 'Which pix key was selected, phone number, CPF, etc',
    pix_data VARCHAR(40) NOT NULL COMMENT 'CPF or CNPJ',
    transaction_id VARCHAR(255) NOT NULL COMMENT 'System generated ID',
    end_to_end_id VARCHAR(255) NOT NULL COMMENT 'ID generated by Government',
    description VARCHAR(40),
    

    FOREIGN KEY (expense_id) REFERENCES expenses(id),
    FOREIGN KEY (source_bank_acc_id) REFERENCES bank_account(id)

);