INSERT INTO currencies (currency_name, currency_flag, currency_symbol, decimal_places)
VALUES
    ('US Dollar', 'USD', '$', 2),
    ('Euro', 'EUR', '€', 2),
    ('Japanese Yen', 'JPY', '¥', 0),
    ('British Pound', 'GBP', '£', 2),
    ('Australian Dollar', 'AUD', 'A$', 2),
    ('Canadian Dollar', 'CAD', 'C$', 2),
    ('Swiss Franc', 'CHF', 'CHF', 2),
    ('Chinese Yuan', 'CNY', '¥', 2),
    ('Hong Kong Dollar', 'HKD', 'HK$', 2),
    ('New Zealand Dollar', 'NZD', 'NZ$', 2),
    ('Swedish Krona', 'SEK', 'kr', 2),
    ('South Korean Won', 'KRW', '₩', 0),
    ('Singapore Dollar', 'SGD', 'S$', 2),
    ('Norwegian Krone', 'NOK', 'kr', 2),
    ('Mexican Peso', 'MXN', 'Mex$', 2),
    ('Indian Rupee', 'INR', '₹', 2),
    ('Russian Ruble', 'RUB', '₽', 2),
    ('South African Rand', 'ZAR', 'R', 2),
    ('Turkish Lira', 'TRY', '₺', 2),
    ('Brazilian Real', 'BRL', 'R$', 0),
    ('Danish Krone', 'DKK', 'kr', 2),
    ('Polish Złoty', 'PLN', 'zł', 2),
    ('Thai Baht', 'THB', '฿', 2),
    ('Indonesian Rupiah', 'IDR', 'Rp', 0),
    ('Hungarian Forint', 'HUF', 'Ft', 0),
    ('Czech Koruna', 'CZK', 'Kč', 2),
    ('Israeli New Shekel', 'ILS', '₪', 2),
    ('Chilean Peso', 'CLP', 'CLP$', 0),
    ('Philippine Peso', 'PHP', '₱', 2),
    ('United Arab Emirates Dirham', 'AED', 'د.إ', 2);