
CREATE TABLE notifications (
    notification_id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    seen BOOLEAN DEFAULT FALSE,
    seen_at TIMESTAMP NULL,
    delete_on TIMESTAMP DEFAULT DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 30 DAY),
    FOREIGN KEY (user_id) REFERENCES finance_app.users(id) ON DELETE CASCADE
);
